export const members= [

  {
    "id": 1,
    "code": "BIL",
    "name": "Bilsa",
    "nslink": "https://www.nationstates.net/nation=bilsa",
    "flagPath": "/src/assets/images/members/bilsa_flag.png",
    "federation": "Bilsa Fuzbal",
    "logoPath": "/src/assets/images/members/bilsa_logo.png",
    "feddispatch": "https://www.nationstates.net/nation=bilsa/detail=factbook/id=2512003",
    "region": "Forest",
    "founded": 2012,
    "affiliation": 2024,
    "score": 0,
    "records": [{
      "tournamentsPlayed": 3,
      "tournamentsWon": 0,
      "totalPoints": 15,
      "matches": 11,
      "wins": 4,
      "draws": 3,
      "losses": 4,
      "goalsFor": 6,
      "goalsAgainst": 4
    }
    ]
  },
  {
    "id": 2,
    "code": "STR",
    "name": "Stralla",
    "nslink": "https://www.nationstates.net/nation=stralla",
    "flagPath": "/src/assets/images/members/stralla_flag.png",
    "federation": "Stralla Fuzbal",
    "logoPath": "/src/assets/images/members/stralla_logo.png",
    "feddispatch": null,
    "region": "Forest",
    "founded": 2020,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 3,
    "code": "JUT",
    "name": "Jutsa",
    "nslink": "https://www.nationstates.net/nation=jutsa",
    "flagPath": "/src/assets/images/members/jutsa_flag.png",
    "federation": "Jutsa Football Association",
    "logoPath": "/src/assets/images/members/jutsa_logo.png",
    "feddispatch": null,
    "region": "Forest",
    "founded": 2022,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 4,
    "code": "ZPH",
    "name": "Zerphen",
    "nslink": "https://www.nationstates.net/nation=zerphen",
    "flagPath": "/src/assets/images/members/zerphen_flag.png",
    "federation": "Zerphen Football Association",
    "logoPath": "/src/assets/images/members/zerphen_logo.png",
    "feddispatch": null,
    "region": "Forest",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 5,
    "code": "CAC",
    "name": "Cacusia",
    "nslink": "https://www.nationstates.net/nation=democratic_republic_of_cacusia",
    "flagPath": "/src/assets/images/members/democratic_republic_of_cacusia_flag.png",
    "federation": "Cacusse Football Federation",
    "logoPath": "/src/assets/images/members/democratic_republic_of_cacusia_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1357240",
    "region": "Forest",
    "founded": 1877,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 6,
    "code": "REA",
    "name": "Reannia",
    "nslink": "https://www.nationstates.net/nation=reannia",
    "flagPath": "/src/assets/images/members/reannia_flag.png",
    "federation": "Reannian Football Association",
    "logoPath": "/src/assets/images/members/reannia_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1189731",
    "region": "Forest",
    "founded": 1556,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 7,
    "code": "ATS",
    "name": "Atsvea",
    "nslink": "https://www.nationstates.net/nation=atsvea",
    "flagPath": "/src/assets/images/members/atsvea_flag.jpeg",
    "federation": "FFA",
    "logoPath": "/src/assets/images/members/atsvea_logo.png",
    "feddispatch": null,
    "region": "Forest",
    "founded": 2020,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 8,
    "code": "RLS",
    "name": "Roless",
    "nslink": "https://www.nationstates.net/nation=roless",
    "flagPath": "/src/assets/images/members/roless_flag.png",
    "federation": "Royal Rolessian Football Federation",
    "logoPath": "/src/assets/images/members/roless_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1578507",
    "region": "Forest",
    "founded": 1986,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 9,
    "code": "EIN",
    "name": "Einswenn",
    "nslink": "https://www.nationstates.net/nation=einswenn",
    "flagPath": "/src/assets/images/members/einswenn_flag.png",
    "federation": "BERSA Einset Football",
    "logoPath": "/src/assets/images/members/einswenn_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=2533546",
    "region": "Forest",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 10,
    "code": "TRZ",
    "name": "The Realizer",
    "nslink": "https://www.nationstates.net/nation=the_realizer",
    "flagPath": "/src/assets/images/members/the_realizer_flag.png",
    "federation": null,
    "logoPath": "/src/assets/images/members/the_realizer_logo.png",
    "feddispatch": null,
    "region": "Forest",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 11,
    "code": "AKE",
    "name": "Anxious and Kevin",
    "nslink": "https://www.nationstates.net/nation=anxious_and_kevin",
    "flagPath": "/src/assets/images/members/anxious_and_kevin_flag.png",
    "federation": "Anxious & Kevin Football Federation",
    "logoPath": "/src/assets/images/members/anxious_and_kevin_logo.png",
    "feddispatch": "https://www.nationstates.net/nation=anxious_and_kevin/detail=factbook/id=1933991",
    "region": "Forest",
    "founded": 2002,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 12,
    "code": "ORC",
    "name": "Orcuo",
    "nslink": "https://www.nationstates.net/nation=orcuo",
    "flagPath": "/src/assets/images/members/orcuo_flag.png",
    "federation": "Orcuo Football Association",
    "logoPath": "/src/assets/images/members/orcuo_logo.png",
    "feddispatch": null,
    "region": "Warzone Sandbox",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 13,
    "code": "CQ",
    "name": "Columbiqash",
    "nslink": "https://www.nationstates.net/nation=columbiqash",
    "flagPath": "/src/assets/images/members/columbiqash_flag.jpg",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "Forest",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 14,
    "code": "TYL",
    "name": "Tylvana",
    "nslink": "https://www.nationstates.net/nation=tylvana",
    "flagPath": "/src/assets/images/members/tylvana_flag.png",
    "federation": null,
    "logoPath": "/src/assets/images/members/tylvana_logo.png",
    "feddispatch": null,
    "region": "Forest",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 15,
    "code": "UMF",
    "name": "United Malay Federation",
    "nslink": "https://www.nationstates.net/nation=united_malay_federation",
    "flagPath": "/src/assets/images/members/umf_flag.png",
    "federation": "United Malay Federation National Football Team",
    "logoPath": "/src/assets/images/members/united_malay_federation_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1589292",
    "region": "Forest",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 16,
    "code": "VH",
    "name": "Verdant Haven",
    "nslink": "https://www.nationstates.net/nation=verdant_haven",
    "flagPath": "/src/assets/images/members/vh_flag.png",
    "federation": "Verdant Haven Football Federation",
    "logoPath": "/src/assets/images/members/verdant_haven_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1569639",
    "region": "Forest",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 17,
    "code": "LUM",
    "name": "Lumiose",
    "nslink": "https://www.nationstates.net/nation=lumiose",
    "flagPath": "/src/assets/images/members/lumiose_flag.png",
    "federation": "Lumiose Football Association",
    "logoPath": "/src/assets/images/members/lumiose_logo.png",
    "feddispatch": "https://www.nationstates.net/nation=lumiose/detail=factbook/id=2536430",
    "region": "Forest",
    "founded": 1881,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 18,
    "code": "RUI",
    "name": "Ruinenlust",
    "nslink": "https://www.nationstates.net/nation=ruinenlust",
    "flagPath": "/src/assets/images/members/ruinenlust_flag.png",
    "federation": null,
    "logoPath": "/src/assets/images/members/ruinenlust_logo.png",
    "feddispatch": null,
    "region": "Forest",
    "founded": 2020,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 19,
    "code": "EPR",
    "name": "Freistaat Ostpreussen",
    "nslink": "https://www.nationstates.net/nation=freistaat_ostpreussen",
    "flagPath": "/src/assets/images/members/op_flag.png",
    "federation": "Ostpreußischer Fußballverband",
    "logoPath": "/src/assets/images/members/freistaat_ostpreussen_logo.png",
    "feddispatch": "https://www.nationstates.net/nation=freistaat_ostpreussen/detail=factbook/id=main",
    "region": "Forest",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 20,
    "code": "BSF",
    "name": "Bisofeyr",
    "nslink": "https://www.nationstates.net/nation=bisofeyr",
    "flagPath": "/src/assets/images/members/bisofeyr_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "Forest",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 21,
    "code": "FUR",
    "name": "Furilisca",
    "nslink": "https://www.nationstates.net/nation=furilisca",
    "flagPath": "/src/assets/images/members/furilisca_flag.png",
    "federation": "Furilisca Fotbolta",
    "logoPath": "/src/assets/images/members/furilisca_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1826702",
    "region": "Forest",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 22,
    "code": "NLK",
    "name": "New Libertalia Kingdom",
    "nslink": "https://www.nationstates.net/nation=new_libertalia_kingdom",
    "flagPath": "/src/assets/images/members/nlk_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "Portugal",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 23,
    "code": "SCH",
    "name": "Schachland",
    "nslink": "https://www.nationstates.net/nation=schachland",
    "flagPath": "/src/assets/images/members/schachland_flag.svg",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "Europe",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 24,
    "code": "YUC",
    "name": "Republic of Yucatan",
    "nslink": "https://www.nationstates.net/nation=republic_of_yucatan",
    "flagPath": "/src/assets/images/members/yucatan_flag.png",
    "federation": "Yucatec Football Federation",
    "logoPath": "/src/assets/images/members/republic_of_yucatan_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1544428",
    "region": "Democratic Socialist Assembly",
    "founded": 1920,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 25,
    "code": "WAS",
    "name": "Washeyye",
    "nslink": "https://www.nationstates.net/nation=washeyye",
    "flagPath": "/src/assets/images/members/washeyye_flag.png",
    "federation": "Washeyye National Football Association",
    "logoPath": "/src/assets/images/members/washeyye_logo.png",
    "feddispatch": "https://www.nationstates.net/page=dispatch/id=1912342",
    "region": "Democratic Socialist Assembly",
    "founded": 2020,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 26,
    "code": "CAT",
    "name": "Cat Army",
    "nslink": "https://www.nationstates.net/nation=cat_army",
    "flagPath": "/src/assets/images/members/cat_army_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "The Region That Has No Big Banks",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 27,
    "code": "RKD",
    "name": "RKD",
    "nslink": "https://www.nationstates.net/nation=rkd",
    "flagPath": "/src/assets/images/members/rkd_flag.png",
    "federation": null,
    "logoPath": "/src/assets/images/members/rkd_logo.png",
    "feddispatch": null,
    "region": "Quiet Cottage on the Edge of the Cosmos",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 28,
    "code": "NAR",
    "name": "Nardin",
    "nslink": "https://www.nationstates.net/nation=nardin",
    "flagPath": "/src/assets/images/members/nardin_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "Europe",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 29,
    "code": "OTL",
    "name": "Ottterland",
    "nslink": "https://www.nationstates.net/nation=ottterland",
    "flagPath": "/src/assets/images/members/ottterland_flag.png",
    "federation": null,
    "logoPath": "/src/assets/images/members/ottterland_logo.png",
    "feddispatch": null,
    "region": "Europe",
    "founded": 2024,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 30,
    "code": "ARE",
    "name": "Aresetia",
    "nslink": "https://www.nationstates.net/nation=aresetia",
    "flagPath": "/src/assets/images/members/aresetia_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "The East Pacific",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 31,
    "code": "SEH",
    "name": "Sehir",
    "nslink": "https://www.nationstates.net/nation=sehir",
    "flagPath": "/src/assets/images/members/sehir_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": "Forest",
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 32,
    "code": "MOZ",
    "name": "Mozolephies",
    "nslink": "https://www.nationstates.net/nation=mozolephies",
    "flagPath": "/src/assets/images/members/mozolephies_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": null,
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    },
    {
    "id": 33,
    "code": "CTC",
    "name": "Clown Town City",
    "nslink": "https://www.nationstates.net/nation=clown_town_city",
    "flagPath": "/src/assets/images/members/ctc_flag.png",
    "federation": null,
    "logoPath": null,
    "feddispatch": null,
    "region": null,
    "founded": null,
    "affiliation": 2024,
    "score": 0,
    "records": [{
    "tournamentsPlayed": 0,
    "tournamentsWon": 0,
    "totalPoints": 0,
    "matches": 0,
    "wins": 0,
    "draws": 0,
    "losses": 0,
    "goalsFor": 0,
    "goalsAgainst": 0
    }]
    }
];
